### ISSUE TITLE
Crashes Sketch on 10.15 Catalina

### ISSUE THREAD

**Issue by greyskymedia** [lifeofmle/symbol-insert#2]
Trying to trigger the insert plugin crashes Sketch. I just upgraded to 10.15.

**Comment by nicholas-evans** [comment]
+1 It also crashed for me.

**Comment by lifeofmle** [comment]
Thanks for raising this issue @greyskymedia @nicholas-evans I will try to resolve in next few days

**Comment by lifeofmle** [comment]
This issue is now fixed with this release https://github.com/lifeofmle/symbol-insert/releases/tag/v1.2.1

The root cause was that there was a change with how Catalina handles webviews used for the popup screen
